service: serverless-go
frameworkVersion: '>= 4.4.4'
useDotenv: true
provider:
  name: aws
  runtime: provided.al2
  region: us-east-2
  stage: ${opt:stage, 'dev'}

functions:
  scraper:
    handler: bootstrap
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: scraper
          method: get
          request:
            parameters:
              querystrings:
                make: true
                model: true
                year: false  

package:
  include:
    - bootstrap 
  exclude:
    - ./**
